// popSampleAction.close();
// var url = 'https://template.neptune-software.com/neptune/sdk/explored_preview?key=' + currentApp;
// diaRun = window.open(url, "RunWrapper", "width=1200, height=850,location=false,left=100,top=50").focus();


// popSampleAction.close();
// var url = 'https://portal.neptune-software.com/app/explored_appdesigner.html?application=' + currentApp;
// diaRun = window.open(url, "RunWrapper", "width=1200, height=850,location=false,left=100,top=50").focus();
